name: "Build LaTex Document"

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic Satzung.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: Satzung
          path: Satzung.pdf
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: "*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
